In [2]:
import pandas as pd
import numpy as np

In [3]:
dat=pd.read_csv("news_headlines.csv")
dat

ID                                              TITLE CATEGORY
0       226435  Google+ rolls out 'Stories' for tricked out ph...        t
1       356684                    Dov Charney's Redeeming Quality        b
2       246926   White God adds Un Certain Regard to the Palm Dog        e
3       318360  Google shows off Androids for wearables, cars,...        t
4       277235         China May new bank loans at 870.8 bln yuan        b
5        13410  Firefox Windows 8 Metro Browser Development Ca...        t
6       186031                     Destiny Beta Kicks Off In July        t
7       213743         Apple & Google's Motorola end legal battle        t
8       155736  UPDATE 2-Facebook Q1 revenue grows 72 percent ...        b
9        98934  Selena Gomez, Justin Bieber Spotted at the Sam...        e
10        1011  Titanfall: Gameplay basics, release date, DLC ...        t
11      242833  Angela Bassett to direct Whitney Houston biopi...        e
12      275148  German Museum Lets You Talk to van Gogh's Regr...        e
13      298735           Iraq crisis fuels concern for oil prices        t
14      400203  BC doctor OK, not in quarantine after Ebola ai...        m
15      323513  GM recalling nearly 29000 Chevrolet Cruzes to ...        t
16      189580           Local Experts Weigh in on Climate Change        t
17      295221  Samsung Reportedly Explored Acquiring Company ...        t
18      265955  'Ghost Stories' by Coldplay Hits No. 1 on Bill...        e
19      239543      Hackers raid eBay, access 145 million records        t
20      101768  Most people ready to just assume Colin Kaepern...        b
21      301818  Sound off: US Patent Office cancels Redskins t...        b
22      110745  Beyonce - Beyonce Makes Surprise Appearance At...        e
23       81068  Mark Cuban: Potential flash crash bigger issue...        b
24       17700             Apple to launch 8GB iPhone 5c tomorrow        t
25        5070  Westhus Reaping Fannie Windfall to Rival Big S...        b
26      120677  US stocks open higher, extending modest rally;...        b
27      107086                             Why KISS won't make up        e
28      248986  Report: Edgar Wright Walked Off Ant-Man After ...        e
29      218526  As I Lay Dying Singer Sentenced To Six Years I...        e
...        ...                                                ...      ...
211179  362706                                         Full Story        m
211180  169818                       Edit Public Profile Sign Out        e
211181  257907  Mick Jagger Says He's "Looking Forward To The ...        e
211182   73013  Johnny Depp wears engagement ring, confirms ru...        e
211183  367152  Samsung's operating profit hits 2-year low in ...        b
211184   97632  Samsung Galaxy S5 goes on sale across the UK t...        t
211185  277055  Uber launches new taxi service to appease Lond...        b
211186  295480  A hidden Picasso? Scientists discover painted-...        e
211187  268165  FAA may let some movie studios use drones for ...        b
211188  265105  Fox News adds small-government actor Stacey Da...        e
211189  293516  UK watchdog urges public, cooks not to wash ra...        m
211190  241429   Hewlett-Packard A Festering Black Swan... Beware        b
211191  378070  Good News for Wall Street: Citi's Trading Reve...        b
211192  180117  Deaths fell after Massachusetts healthcare ove...        m
211193  222983                                      Pharmacy Down        m
211194   58790                     'Noah' powerful and unsettling        e
211195  178211  Top 10 Cinco de Mayo Bars and Restaurants in C...        e
211196  413950  European Probe Has 5 Potential Drop Zones for ...        t
211197  391967  Report: Microsoft's cuts include the EMEA Xbox...        t
211198  267956  Major Allergan shareholder seeks to replace di...        b
211199   57685  Facebook to use drones, satellites to provide ...        t
211200  122864           Ford Will Of

In [4]:
np.unique(dat['CATEGORY'],return_counts=True)

(array(['b', 'e', 'm', 't'], dtype=object),
 array([58093, 76264, 22886, 53966], dtype=int64))

In [5]:
dat["CATEGORY"].unique()

array(['t', 'b', 'e', 'm'], dtype=object)

In [6]:
corpus=["this is sentence one","this is sentence two","this is sentence three"]

In [7]:
from sklearn.feature_extraction import text

In [9]:
#countVectorizer creates an object  cnt of class CountVectorizer
#CountVectorizer and
#TfidTransformer are feature extraction objects

cnt=text.CountVectorizer(input=corpus)

In [10]:
cnt

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8',
        input=['this is sentence one', 'this is sentence two', 'this is sentence three'],
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [12]:
#fit will select the unique words/features
#transform will convert to numeric binary.

cnt_matrix=cnt.fit_transform(corpus)

cnt_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [13]:
cnt_matrix.toarray()

array([[1, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 0]], dtype=int64)

In [14]:
type(cnt_matrix)

scipy.sparse.csr.csr_matrix

In [16]:
cnt.get_feature_names()

['is', 'one', 'sentence', 'this', 'three', 'two']

In [18]:
pd.DataFrame(cnt_matrix.toarray(),columns=cnt.get_feature_names())

is  one  sentence  this  three  two
0   1    1         1     1      0    0
1   1    0         1     1      0    1
2   1    0         1     1      1    0

In [19]:
sent4=["This is sentence four"]

In [20]:
cnt.fit_transform(sent4).toarray()

array([[1, 1, 1, 1]], dtype=int64)

In [21]:
type(cnt.transform(sent4).toarray())

numpy.ndarray

In [22]:
pd.DataFrame(cnt.transform(sent4).toarray(),columns=cnt.get_feature_names())

four  is  sentence  this
0     1   1         1     1

In [23]:

tfidf=text.TfidfVectorizer(input=corpus,ngram_range=(2,2))

#tfidf=text.CountVectorizer(input=corpus,ngram_range=(2,2))

In [24]:
#tfidf_matrix=tfidf.fit_transform(corpus)

tfidf_matrix=tfidf.fit_transform(corpus)

In [25]:
#pd.DataFrame(tfidf_matrix.toarray(),columns=tfidf.get_feature_names())

pd.DataFrame(tfidf_matrix.toarray(),columns=tfidf.get_feature_names())


is sentence  sentence one  sentence three  sentence two   this is
0     0.453295      0.767495        0.000000      0.000000  0.453295
1     0.453295      0.000000        0.000000      0.767495  0.453295
2     0.453295      0.000000        0.767495      0.000000  0.453295

In [30]:
dat=pd.read_csv("news_headlines.csv")

In [31]:
dat.head()

ID                                              TITLE CATEGORY
0  226435  Google+ rolls out 'Stories' for tricked out ph...        t
1  356684                    Dov Charney's Redeeming Quality        b
2  246926   White God adds Un Certain Regard to the Palm Dog        e
3  318360  Google shows off Androids for wearables, cars,...        t
4  277235         China May new bank loans at 870.8 bln yuan        b

In [32]:
X=dat["TITLE"]
Y=dat["CATEGORY"]

In [34]:
#dat=pd.read_excel("./pandas_simple.xlsx")

In [35]:
X=dat["text"]
Y=dat["Root_Cause"]

KeyError: 'text'

In [6]:
Y.head()

0      Cloud-Post Go Live
1    Cloud-Implementation
2      Cloud-Post Go Live
3      Cloud-Post Go Live
4      Cloud-Post Go Live
Name: Root_Cause, dtype: object

In [7]:

from sklearn.model_selection import  train_test_split

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=200)

In [9]:
X_train.tolist()

['unable enable multicurrency account non ledger currency',
 'encounter application error run account analysis contra account report',
 'error webcenter',
 'restrict sr content',
 'approval rule r',
 'aip integration sign detail require',
 'vat tax calculation ocr invoice',
 'document number argentina',
 'impl spt page composer change journals possible',
 'need sql check account budget',
 'bank account give bank account num currency code find',
 'unable inactivate employee bank account fusion expense',
 'tax cloud clculo incorreto para icms com ipi compondo base',
 'impl spt statement line line reconciliation disable bank reconciliation',
 'impl spt error try decrease credit limit customer header level use recommendation',
 'customer status upload rmc',
 'unable post sub ledger transactions general ledger',
 'balance sgmnt value receivables show cmpny value instead assign ledger',
 'asset revaluation problem use index price',
 'impl spt add cross validation rule cvr personalize budget 

In [10]:
#tfidf=text.TfidfVectorizer(input=X_train.tolist(),stop_words="english",max_features=1000)


tfidf=text.TfidfVectorizer(input=X_train.tolist(),stop_words="english",max_features=1000)


NameError: name 'text' is not defined

In [43]:
#X_tr=tfidf.fit_transform(X_train.tolist())


X_tr=tfidf.fit_transform(X_train.tolist())

In [46]:
X_tr_matrix=X_tr.toarray()
X_tr_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
pd.DataFrame(X_tr_matrix,columns=tfidf.get_feature_names())

10  100        11   12   13   14   15        16   17   18 ...   \
0       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
1       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
2       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
3       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
4       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
5       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
6       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
7       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
8       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
9       0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
10      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
11      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
12      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
13      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
14      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
15      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
16      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
17      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
18      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
19      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
20      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
21      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
22      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
23      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
24      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
25      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
26      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
27      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
28      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
29      0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
...          ...  ...       ...  ...  ...  ...  ...       ...  ...  ... ...    
168937  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168938  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168939  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168940  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168941  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168942  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168943  0.000000  0.0  0.443687  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168944  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168945  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168946  0.402658  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168947  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168948  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168949  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168950  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168951  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168952  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168953  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168954  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  0.0  0.0 ...    
168955  0.0000

In [48]:
#X_te=tfidf.transform(X_test.tolist())

X_te=tfidf.transform(X_test.tolist())


In [49]:
Y_train.unique()

array(['m', 't', 'b', 'e'], dtype=object)

In [50]:
#from sklearn.preprocessing  import LabelEncoder
#Here Label encoder is used to convdert any column to numerical values depending upon clases


from sklearn.preprocessing import LabelEncoder

In [51]:
#enc=LabelEncoder()

enc=LabelEncoder()

In [52]:
#Y_tr=enc.fit_transform(Y_train)

Y_tr=enc.fit_transform(Y_train)

In [53]:
Y_tr

array([2, 3, 3, ..., 3, 1, 2], dtype=int64)

In [54]:
#Y_te=enc.transform(Y_test)

Y_te=enc.transform(Y_test)

In [55]:
#from sklearn.linear_model import LogisticRegression



from sklearn.linear_model import LogisticRegression

In [56]:
# clf=LogisticRegression(multi_class='multinomial',penalty='l2',solver="lbfgs")

clf=LogisticRegression(multi_class="multinomial",penalty='l2',solver="lbfgs")

#here L2 is regularizer and lbfgs is optimiser

In [57]:
LogisticRegression()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [58]:
import sklearn.model_selection as model_selection

In [59]:
#param_grid={'C':np.arange(0,1,0.1)}

param_grid= {'C':np.arange(0,1,0.1)}

#to perform Grid Search between 0 and 1 ,at an interval of 0.1

In [120]:
param_grid

{'C': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])}

In [60]:
#mod=model_selection.GridSearchCV(clf,param_grid=param_grid,n_jobs=-1,verbose=10)

mod=model_selection.GridSearchCV(clf,param_grid=param_grid,n_jobs=-1,verbose=10)


#n_jobs:asked to use multiple cores in the system if available
#verbose:controls the verbose 



In [61]:
#mod.fit(X_tr,Y_tr)


mod.fit(X_tr,Y_tr)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:   19.4s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:   35.4s
[Parallel(n_jobs=-1)]: Done  19 out of  30 | elapsed:   53.9s remaining:   31.2s
[Parallel(n_jobs=-1)]: Done  23 out of  30 | elapsed:  1.0min remaining:   19.1s
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:  1.1min remaining:    7.5s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:  1.2min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=10)

In [62]:
mod.best_params_

{'C': 0.9}

In [63]:
#mod.score(X_te,Y_te)
mod.score(X_te,Y_te)


0.8278253870555371

In [64]:
#head_text='Bank Loans'


##walmart announces quaterley revenue
##Next movie in the IMAX


head_text='Many more movie releases this weekend'

In [65]:
#tfidf_headline=tfidf.transform([head_text])


tfidf_headline=tfidf.transform([head_text])

In [66]:
#mod.predict(tfidf_headline)


mod.predict(tfidf_headline)

array([1], dtype=int64)

In [67]:
#enc.inverse_transform(0)


enc.inverse_transform(1)

'e'

In [70]:
#from sklearn import naive_bayes,svm,metrics,ensemble

from sklearn import naive_bayes,svm,metrics,ensemble



In [68]:
def train_model(classifier,feature_vector_train,label,feature_vector_valid):
    classifier.fit(feature_vector_train,label)
    predictions=classifier.predict(feature_vector_valid)
    return metrics.accuracy_score(predictions,Y_te)

In [71]:
#nb=train_model(naive_bayes.MultinomialNB(),X_tr,Y_tr,X_te)


nb=train_model(naive_bayes.MultinomialNB(),X_tr,Y_tr,X_te)


In [66]:
print(nb)

0.8137162066190048


In [67]:
RF=train_model(ensemble.RandomForestClassifier(),X_tr,Y_tr,X_te)

In [68]:
print(RF)

0.8435916859997159
